### ISSUE TITLE
Atmosphere images is vague, can we be more specific?

### ISSUE THREAD

**Issue by JasonJWilliamsNY** [CyVerse-learning-materials/ez_quickstart#2]
1. First, are we sure that all featured images have ez? I think that is true of the base images, but there is at least one non-base image that is featured. 
2. The link to featured images shows more than the featured images. Should we provide a specific list of images and versions. 
3. For the purposes of the quick start, we should choose one specific image and link to that so folks can launch it (i.e. https://atmo.cyverse.org/application/images/1453).

**Comment by bjoyce3** [comment]
1. Yes, all running instances have ez. It's not part of the imaging process. These are ansible playbooks that the user calls from Atmosphere.
2. That link is to any image. The default in Atmosphere is to show featured images. That will be changing when the new search modal is launched in Atmo/Jetstream. 
3. Will linking to only a single image cause confusion that this can be used on any image?

**Comment by JasonJWilliamsNY** [comment]
1. Nice
2/3. Right now, when there are multiple choices of something that can be used (i.e. an image) we give a specific one to use with this quickstart/tutorial. As long as its explained should not be confusing.

**Comment by bjoyce3** [comment]
Updated with a specific example and corrected requirement tables.
